version: "3"
services:
  db:
    image: mysql:8.0.30
    ports:
      - "30000:3306"
    environment:
      - MYSQL_DATABASE=docker
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=Sagarsi@786
      - MYSQL_ROOT_PASSWORD=Sagarsi@786
      
    # volumes:
    #   - ./db:/docker-entrypoint-initdb.d/:ro
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - database=docker
        - password=Sagarsi@786
    command: python manage.py runserver 0.0.0.0:8000  
    # entrypoint: ["./wait.sh"]
    ports:
      - "8000:8000"
    depends_on: 
      - db
    env_file:
      - .env
    